# Generated by Django 4.2.7 on 2023-11-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='di',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
