# Generated by Django 4.2.7 on 2023-11-16 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIGES', '0002_customuser_di'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('imagen_perfil', models.ImageField(upload_to='perfiles/')),
                ('imagen_documento', models.ImageField(upload_to='documentos/')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('di_tipo', models.CharField(max_length=255)),
                ('nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('paisResidencia', models.CharField(max_length=255)),
                ('di', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
