# Generated by Django 4.2.7 on 2023-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGES', '0003_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paisResidencia',
            field=models.CharField(max_length=50),
        ),
    ]
