# Generated by Django 4.2.7 on 2023-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGES', '0004_alter_customuser_paisresidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='carrera',
            field=models.CharField(default='nose', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='carrera',
            field=models.CharField(default='nose', max_length=50),
            preserve_default=False,
        ),
    ]
