# Generated by Django 4.2.7 on 2023-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGES', '0005_curriculum_carrera_customuser_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
    ]
